### ISSUE TITLE
Broken since move to MDN Observatory

### ISSUE THREAD

**Issue by scarytom** [mozilla/observatory-cli#52]
The cli appears to no longer function owing to the migration of the Mozilla Observatory to the new MDN observatory.  There might be a new API endpoint to use, but I'm not sure.  The MDN documentation is pretty unhelpful regarding the migration of APIs.

**Comment by argl** [comment]
Thank you for reporting this! The old API is still working, but there were some operational issues leading to 502 errors on some requests. These are a coincidence, nothing changed yet on that API. We are planning to sunset the old API in a couple of months though, with appropriate migration guides released in time.

**Comment by gprovostqa** [comment]
Is there anything open for the operational issues then? I've been having those failures since July 25th.

**Comment by scarytom** [comment]
> there were some operational issues leading to 502 errors on some requests.

Thanks for responding @argl. Your response implies these failures were intermittent and are now fixed.  This problem seems to affect 100% of requests and is ongoing since July 22nd

**Comment by argl** [comment]
I checked the API and it worked for me, but I still see problems on the backend which are being worked on with high priority. The symptom are timeouts resulting in 502 errors. Please hang in there while we are resolving things.

**Comment by argl** [comment]
Changes have been deployed, things should work properly now. Just to make sure, it is the `https://http-observatory.security.mozilla.org` endpoint that is failing for you?

**Comment by scarytom** [comment]
we are hitting https://http-observatory.security.mozilla.org/api/v1
It does appear to be working again now.  Thank you.

**Comment by argl** [comment]
Changes have been deployed, things should work properly now. Just to make sure, it is the `https://http-observatory.security.mozilla.org` endpoint that is failing for you?
